project:
  type: website
  output-dir: docs

website:
  title: "Train the Trainer: Student Track: Pedagogical Content"
  page-navigation: true
  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
      - href: help.qmd
        text: Help
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Teaching Open Research"
        contents:
          - href: materials/teaching-open-research/Core-Didactic-Principles/Core-Didactic-Principles.qmd
          - href: materials/teaching-open-research/Concept-Planning/Concept-Planning.qmd
          - href: materials/teaching-open-research/Creating-Positive-Learning-Environment/Creating-Positive-Learning-Environment.qmd
          - href: materials/teaching-open-research/Activation-Methods/Activation-Methods.qmd

      - section: "Leadership in Open Research"
        contents:
          - href: materials/leadership-open-research/Citation-Politics/Citation-Politics.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: website-custom.css
    toc: true
    include-in-header:
      - file: matomo-analytics.html
