project:
  type: website
  output-dir: docs

website:
  title: "Train the Trainer: Student Track: Pedagogical Content"
  page-navigation: true
  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
      - href: help.qmd
        text: Help
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Teaching Open Research"
        contents:
          - href: materials/teaching-open-research/core-didactic-principles/core-didactic-principles.qmd
          - href: materials/teaching-open-research/concept-planning/concept-planning.qmd
          - href: materials/teaching-open-research/creating-learning-environment/creating-learning-environment.qmd
          - href: materials/teaching-open-research/activation-methods/activation-methods.qmd

      - section: "Leadership in Open Research"
        contents:
          - href: materials/leadership-open-research/citation-politics/citation-politics.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: website-custom.css
    toc: true
    include-in-header:
      - file: matomo-analytics.html
