project:
  type: website
  output-dir: docs

website:
  title: "Train the Trainer: Student Track: Pedagogical Content"
  page-navigation: true
  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
      - href: help.qmd
        text: Help
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Teaching Open Research"
        contents:
          - href: teaching-open-research/core-didactic-principles/index.qmd
          - href: teaching-open-research/concept-planning/index.qmd
          - href: teaching-open-research/creating-learning-environment/index.qmd
          - href: teaching-open-research/activation-methods/index.qmd

      - section: "Leadership in Open Research"
        contents:
          - href: leadership-open-research/citation-politics/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: assets/website-custom.css
    toc: true
    include-in-header:
      - file: matomo-analytics.html
