---
title: "About"
date: 2026-08-28
citation:
  type: "webpage"
  title: "Pedagogical tools for teaching open research"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/train-the-trainer-student-track-pedagogy/
  version: 0.0.1
author:
  - name: Sarah von Grebmer zu Wolfsthurn
    roles: [conceptualization, methodology, project administration, supervision, writing - original draft, writing - editing & review]
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0002-6413-3895
  - name: Sara Middleton
    roles: [conceptualization, methodology, writing - original draft, writing - editing & review]
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0001-5307-8029
  - name: Malika Ihle
    roles: [conceptualization, supervision, writing - editing & review]
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0002-3242-5981
  - name: Felix Schönbrodt
    roles: [conceptualization, supervision, writing - editing & review]
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0002-8282-3910
---

## Contributors

This site was authored by Sarah von Grebmer zu Wolfsthurn, Sara Middleton, Malika Ihle, and Felix Schönbrodt. Additional contributions and reviews were provided by Sophie Renard and Flavio Azevedo.

## Licenses

The overall project is available under the [**CC BY-SA 4.0**](https://creativecommons.org/licenses/by-sa/4.0/) license found at [LICENSE](LICENSE.md); all code without any narrative text is also (at your option) available under the [**CC0 1.0 Universal**](https://creativecommons.org/publicdomain/zero/1.0/) license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

## Notes

This tutorial was primarily written in 2026 using [Quarto](https://quarto.org/). Major changes to Quarto can be found at the [Quarto website](https://quarto.org/) for the most up-to-date information, and to confirm that our tutorial is not out-of-date.

## Tutorial Template Quarto Extension

This tutorial was written using the [`lmu-osc/tutorial-template`](https://github.com/lmu-osc/tutorial-template) Quarto extension [@callahan2026].

::: {#refs}
:::

## How to Cite

**To cite this tutorial, please refer to the project's [CITATION.cff](CITATION.cff) file or use the BibTeX citation provided in the appendix below.**
